with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: mocks
filename: "{{.MockName}}.go"
packages:
  todo-service/internal/domain/ports:
    interfaces:
      FileStorage:
      StreamPublisher:
      TodoRepository:
      TransactionManager: 