// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"
	ports "todo-service/internal/domain/ports"

	mock "github.com/stretchr/testify/mock"
)

type MockTransactionManager struct {
	mock.Mock
}

type MockTransactionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionManager) EXPECT() *MockTransactionManager_Expecter {
	return &MockTransactionManager_Expecter{mock: &_m.Mock}
}

func (_m *MockTransactionManager) DoInTx(ctx context.Context, fn func(ports.TodoRepository) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for DoInTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(ports.TodoRepository) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type MockTransactionManager_DoInTx_Call struct {
	*mock.Call
}

func (_e *MockTransactionManager_Expecter) DoInTx(ctx interface{}, fn interface{}) *MockTransactionManager_DoInTx_Call {
	return &MockTransactionManager_DoInTx_Call{Call: _e.mock.On("DoInTx", ctx, fn)}
}

func (_c *MockTransactionManager_DoInTx_Call) Run(run func(ctx context.Context, fn func(ports.TodoRepository) error)) *MockTransactionManager_DoInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(ports.TodoRepository) error))
	})
	return _c
}

func (_c *MockTransactionManager_DoInTx_Call) Return(_a0 error) *MockTransactionManager_DoInTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionManager_DoInTx_Call) RunAndReturn(run func(context.Context, func(ports.TodoRepository) error) error) *MockTransactionManager_DoInTx_Call {
	_c.Call.Return(run)
	return _c
}

func NewMockTransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionManager {
	mock := &MockTransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
