// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "todo-service/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

type MockStreamPublisher struct {
	mock.Mock
}

type MockStreamPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamPublisher) EXPECT() *MockStreamPublisher_Expecter {
	return &MockStreamPublisher_Expecter{mock: &_m.Mock}
}

func (_m *MockStreamPublisher) PublishTodoCreated(ctx context.Context, todo *entities.TodoItem) error {
	ret := _m.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for PublishTodoCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.TodoItem) error); ok {
		r0 = rf(ctx, todo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type MockStreamPublisher_PublishTodoCreated_Call struct {
	*mock.Call
}

func (_e *MockStreamPublisher_Expecter) PublishTodoCreated(ctx interface{}, todo interface{}) *MockStreamPublisher_PublishTodoCreated_Call {
	return &MockStreamPublisher_PublishTodoCreated_Call{Call: _e.mock.On("PublishTodoCreated", ctx, todo)}
}

func (_c *MockStreamPublisher_PublishTodoCreated_Call) Run(run func(ctx context.Context, todo *entities.TodoItem)) *MockStreamPublisher_PublishTodoCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.TodoItem))
	})
	return _c
}

func (_c *MockStreamPublisher_PublishTodoCreated_Call) Return(_a0 error) *MockStreamPublisher_PublishTodoCreated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStreamPublisher_PublishTodoCreated_Call) RunAndReturn(run func(context.Context, *entities.TodoItem) error) *MockStreamPublisher_PublishTodoCreated_Call {
	_c.Call.Return(run)
	return _c
}

func NewMockStreamPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamPublisher {
	mock := &MockStreamPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
